### ISSUE TITLE
Compile error on Alpine linux

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#692]
Originally reported by @z3ntu [here](https://github.com/MirServer/mir/pull/687#issuecomment-452424289):
...
Also as I've got -Werror enabled now here:
```
/home/luca/mir/src/platforms/evdev/evdev_device_detection.cpp: In constructor '{anonymous}::DeviceInfo::DeviceInfo(const mir::Fd&)':
/home/luca/mir/src/platforms/evdev/evdev_device_detection.cpp:65:19: error: overflow in conversion from 'long unsigned int' to 'int' changes value from '2147763465' to '-2147203831' [-Werror=overflow]
     if (ioctl(fd, EVIOCGPROP(sizeof property_bit_mask), property_bit_mask) < 1)
                   ^~~~~~~~~~
```

**Comment by AlanGriffiths** [comment]
AFAICS this use is idiomatic.

You're apparently using a library where ioctl takes a signed int (as documented by Posix) while EVIOCGPROP returns a long unsigned int (which also seems reasonable for what is effectively bitfields).

From the error message it is clear that bit 31 is set which leads to the (presumably benign) diagnostic.

**Comment by AlanGriffiths** [comment]
@z3ntu could you confirm this is fixed by #693?

**Comment by z3ntu** [comment]
Yes, the compilation gets further now.

**Comment by z3ntu** [comment]
Well actually there are more warnings :wink: 
```
/home/luca/mir/src/common/posix_rw_mutex.cpp: In constructor 'mir::PosixRWMutex::PosixRWMutex(mir::PosixRWMutex::Type)':
/home/luca/mir/src/common/posix_rw_mutex.cpp:53:38: error: unused parameter 'type' [-Werror=unused-parameter]
 mir::PosixRWMutex::PosixRWMutex(Type type)
                                 ~~~~~^~~~
```
(caused by #636)

**Comment by AlanGriffiths** [comment]
@z3ntu, please raise a new issue.
