### ISSUE TITLE
FTBFS: unused_result in run_mir.cpp

### ISSUE THREAD

**Issue by Saviq** [MirServer/mir#2663]
Introduced in #2660 

https://github.com/MirServer/mir/blob/c308112149638d177b7979e0802becd3a19c9b8e/src/server/run_mir.cpp#L161-L163

```
/<<PKGBUILDDIR>>/src/server/run_mir.cpp: In function ‘void {anonymous}::fatal_signal_cleanup(int, siginfo_t*, void*)’:
/<<PKGBUILDDIR>>/src/server/run_mir.cpp:163:32: error: ignoring return value of ‘ssize_t write(int, const void*, size_t)’ declared with attribute ‘warn_unused_result’ [-Werror=unused-result]
  163 |         static_cast<void>(write(STDERR_FILENO, warning, len));
      |                           ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by Saviq** [comment]
Urm.

```
/<<PKGBUILDDIR>>/src/server/run_mir.cpp:165:20: error: ignoring return value of ‘ssize_t write(int, const void*, size_t)’ declared with attribute ‘warn_unused_result’ [-Werror=unused-result]
  165 |         (void)write(STDERR_FILENO, warning, len);
      |               ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```
