### ISSUE TITLE
Mir tries to link clients with wrong Wayland libraries since Cmake 3.22+

### ISSUE THREAD

**Issue by n3rdopolis** [MirServer/mir#2507]
It seems that cmake 3.22 causes Mir examples to link out of order.

Here is what I am compiling it with
```
cmake -Wno-dev . -DCMAKE_INSTALL_PREFIX=$INSTALLDIR -DCMAKE_PREFIX_PATH=$INSTALLDIR -DCMAKE_BUILD_TYPE=MinSizeRel -DLIB_INSTALL_DIR=$INSTALLDIR/lib/$(dpkg-architecture -qDEB_HOST_MULTIARCH) -DMIR_ENABLE_TESTS=OFF -DMIR_BUILD_PLATFORM_EGLSTREAM_KMS=OFF -DMIR_USE_LD=ld
```

Here are some relevant variables;
```
export INSTALLDIR=/opt
export PKG_CONFIG_PATH=$INSTALLDIR/lib/$DEB_HOST_MULTIARCH/pkgconfig:$INSTALLDIR/lib/pkgconfig/:$INSTALLDIR/share/pkgconfig/
export LD_LIBRARY_PATH=$INSTALLDIR/lib/$DEB_HOST_MULTIARCH:$INSTALLDIR/lib:/usr/local/lib/$DEB_HOST_MULTIARCH:/usr/lib/$DEB_HOST_MULTIARCH:/usr/local/lib:/usr/lib

```

I get this below error, and I found out that it's because it's trying to use the older libwayland in /usr instead of in /opt
```
[100%] Linking CXX executable ../../bin/miral-kiosk.bin
/usr/bin/ld: ../example-server-lib/libexample-shell-lib.a(wayland_shm.cpp.o): in function `WaylandShmBuffer::~WaylandShmBuffer()':
/opt/include/wayland-client-protocol.h:2025: undefined reference to `wl_proxy_marshal_flags'
/usr/bin/ld: ../example-server-lib/libexample-shell-lib.a(wayland_shm.cpp.o): in function `WaylandShm::get_buffer(mir::geometry::Size, mir::geometry::detail::IntWrapper<mir::geometry::StrideTag>)':
/opt/include/wayland-client-protocol.h:1940: undefined reference to `wl_proxy_marshal_flags'
/usr/bin/ld: /opt/include/wayland-client-protocol.h:1373: undefined reference to `wl_proxy_marshal_flags'
/usr/bin/ld: ../example-server-lib/libexample-shell-lib.a(wayland_shm.cpp.o): in function `std::_Sp_counted_ptr_inplace<WaylandShmPool, std::allocator<WaylandShmPool>, (__gnu_cxx::_Lock_policy)2>::_M_dispose()':
/opt/include/wayland-client-protocol.h:1391: undefined reference to `wl_proxy_marshal_flags'
/usr/bin/ld: ../example-server-lib/libexample-shell-lib.a(sw_splash.cpp.o): in function `SwSplash::Self::operator()(wl_display*)':
/opt/include/wayland-client-protocol.h:1040: undefined reference to `wl_proxy_marshal_flags'
/usr/bin/ld: ../example-server-lib/libexample-shell-lib.a(wayland_app.cpp.o):/opt/include/wayland-client-protocol.h:1177: more undefined references to `wl_proxy_marshal_flags' follow
collect2: error: ld returned 1 exit status
make[2]: *** [examples/miral-kiosk/CMakeFiles/miral-kiosk.dir/build.make:124: bin/miral-kiosk.bin] Error 1
make[1]: *** [CMakeFiles/Makefile2:3383: examples/miral-kiosk/CMakeFiles/miral-kiosk.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Linking CXX executable ../../bin/mir_demo_server.bin
[100%] Built target mir_demo_server
[100%] Linking CXX static library libmiral-spinner.a
[100%] Built target miral-spinner
```

**Comment by wmww** [comment]
I can not repro with a clean build on Arch with cmake 3.23.2.

**Comment by n3rdopolis** [comment]
Well, yeah, that's kind of the problem, I'm using Debian Stable, and it
must have  libwayland in /usr older than 1.20 because I found that symbol
is in Wayland 1.20 or greater. My libwayland in /opt is newer than 1.20,
but since I started using Cmake 3.22 instead of 3.21, and despite my
variables, it tries to link against the older libwayland. If I eliminate
the older libwayland as a test, the linking works, but that is a bad
workaround

**Comment by n3rdopolis** [comment]
This is on bullseye, the version of libwayland under their /usr is too old for Mir, however I use my own build libwayland which is newer. Along with CMake, It was working fine with CMake 3.21, however since CMake 3.22 it's searching the libraries in the wrong order, and linking with the one under /usr instead of /opt as it has been doing

I build other things, but it seems CMake changed something in Mir, and I am not enough of a CMake guy to know what to look for

**Comment by AlanGriffiths** [comment]
@n3rdopolis ultimately CMake gets the linker options from package config. I (obviously) don't have an Debian system to hand with your local build of libwayland. All I can do is provide some information to help you diagnose what is incorrectly set up in that environment.

On Ubuntu 22.04 package config returns the following:

```
$ pkg-config --libs wayland-client
-lwayland-client
```

You should probably be seeing a result including `-L/opt/...` (unless that is already a system path, which seems unlikely).

You can check which directories are searched for package config files with:

```
pkg-config pkg-config --variable pc_path
```

You need that to be picking up the .pc from your install under /opt in preference to that in /usr

**Comment by n3rdopolis** [comment]
The first one does return the one under /opt   
the second one appears to ignore my $PKG_CONFIG_PATH and is all /usr and /usr/local 
Thanks for this, I will look into it further

**Comment by AlanGriffiths** [comment]
Looking again at your listing...

As well as failing to link `miral-kiosk`, you are successfully building `mir_demo_server` and `miral-spinner`.

That _does_ sound like a problem in the CMakeLists.txt

Could you try the effect of changing the last line of `examples/example-server-lib/CMakeLists.txt`

```diff
-target_link_libraries(example-shell-lib PUBLIC miral PRIVATE ${WAYLAND_CLIENT_LIBRARIES} ${FREETYPE_LIBRARIES})
+target_link_libraries(example-shell-lib PUBLIC miral PRIVATE ${WAYLAND_CLIENT_LDFLAGS} ${FREETYPE_LDFLAGS})
```

**Comment by n3rdopolis** [comment]
Still seems to have some problems
```
[ 96%] Built target example-shell-lib
[ 96%] Generating spinner_logo.h
[ 97%] Generating spinner_glow.h
[ 97%] Building CXX object examples/miral-kiosk/CMakeFiles/miral-kiosk.dir/kiosk_main.cpp.o
[ 98%] Building CXX object examples/mir_demo_server/CMakeFiles/mir_demo_server.dir/glog_logger.cpp.o
[100%] Building CXX object examples/miral-kiosk/CMakeFiles/miral-kiosk.dir/kiosk_window_manager.cpp.o
[100%] Building CXX object examples/mir_demo_server/CMakeFiles/mir_demo_server.dir/server_example.cpp.o
[100%] Building CXX object examples/mir_demo_server/CMakeFiles/mir_demo_server.dir/server_example_test_client.cpp.o
[100%] Linking CXX shared library ../../lib/libmiroil.so
[100%] Building CXX object examples/miral-shell/spinner/CMakeFiles/miral-spinner.dir/eglspinner.cpp.o
[100%] Building CXX object examples/miral-shell/spinner/CMakeFiles/miral-spinner.dir/eglapp.cpp.o
[100%] Built target miroil
[100%] Building CXX object examples/miral-shell/spinner/CMakeFiles/miral-spinner.dir/miregl.cpp.o
[100%] Linking CXX executable ../../bin/miral-kiosk.bin
/usr/bin/ld: ../example-server-lib/libexample-shell-lib.a(wayland_shm.cpp.o): in function `WaylandShmBuffer::~WaylandShmBuffer()':
/opt/include/wayland-client-protocol.h:2025: undefined reference to `wl_proxy_marshal_flags'
/usr/bin/ld: ../example-server-lib/libexample-shell-lib.a(wayland_shm.cpp.o): in function `WaylandShm::get_buffer(mir::geometry::Size, mir::geometry::detail::IntWrapper<mir::geometry::StrideTag>)':
/opt/include/wayland-client-protocol.h:1940: undefined reference to `wl_proxy_marshal_flags'
/usr/bin/ld: /opt/include/wayland-client-protocol.h:1373: undefined reference to `wl_proxy_marshal_flags'
/usr/bin/ld: ../example-server-lib/libexample-shell-lib.a(wayland_shm.cpp.o): in function `std::_Sp_counted_ptr_inplace<WaylandShmPool, std::allocator<WaylandShmPool>, (__gnu_cxx::_Lock_policy)2>::_M_dispose()':
/opt/include/wayland-client-protocol.h:1391: undefined reference to `wl_proxy_marshal_flags'
/usr/bin/ld: ../example-server-lib/libexample-shell-lib.a(sw_splash.cpp.o): in function `SwSplash::Self::operator()(wl_display*)':
/opt/include/wayland-client-protocol.h:1040: undefined reference to `wl_proxy_marshal_flags'
/usr/bin/ld: ../example-server-lib/libexample-shell-lib.a(wayland_app.cpp.o):/opt/include/wayland-client-protocol.h:1177: more undefined references to `wl_proxy_marshal_flags' follow
collect2: error: ld returned 1 exit status
make[2]: *** [examples/miral-kiosk/CMakeFiles/miral-kiosk.dir/build.make:124: bin/miral-kiosk.bin] Error 1
make[1]: *** [CMakeFiles/Makefile2:3383: examples/miral-kiosk/CMakeFiles/miral-kiosk.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Linking CXX static library libmiral-spinner.a
[100%] Built target miral-spinner
[100%] Linking CXX executable ../../bin/mir_demo_server.bin
[100%] Built target mir_demo_server
make: *** [Makefile:146: all] Error 2
```

**Comment by AlanGriffiths** [comment]
To clarify: `miral-kiosk` is the only binary that has this problem?

What are the contents of `examples/miral-kiosk/CMakeFiles/miral-kiosk.dir/link.txt`? (Ideally from working and non-working CMake versions)

**Comment by n3rdopolis** [comment]
I could have sworn I saw mir-spinner in there earlier

Oh man, at glance, they look nearly the same
Bad:
/usr/bin/c++ -Os -Wno-error -pthread -g -Wall -fno-strict-aliasing -pedantic -Wnon-virtual-dtor -Wextra -fPIC  -Wno-mismatched-tags -Wno-psabi -Os -DNDEBUG  -Wl,--as-needed -Wl,--no-undefined CMakeFiles/miral-kiosk.dir/kiosk_main.cpp.o CMakeFiles/miral-kiosk.dir/kiosk_window_manager.cpp.o -o ../../bin/miral-kiosk.bin  ../example-server-lib/libexample-shell-lib.a ../../lib/libmiral.so.4 ../../lib/libmircommon.so.9 ../../lib/libmircookie.so.2 -L/usr/lib/x86_64-linux-gnu -lnettle /usr/lib/x86_64-linux-gnu/libboost_date_time.so.1.74.0 /usr/lib/x86_64-linux-gnu/libboost_program_options.so.1.74.0 /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.74.0 /usr/lib/x86_64-linux-gnu/libboost_iostreams.so.1.74.0 -ldl /opt/lib/x86_64-linux-gnu/libxkbcommon.so ../../lib/libmircore.so.2 /usr/lib/x86_64-linux-gnu/libboost_system.so.1.74.0 -lwayland-client -lfreetype -Wl,-rpath-link,/srcbuild/mir/lib 

Good:
/usr/bin/c++ -Os -Wno-error -pthread -g -Wall -fno-strict-aliasing -pedantic -Wnon-virtual-dtor -Wextra -fPIC  -Wno-mismatched-tags -Wno-psabi -Os -DNDEBUG  -Wl,--as-needed -Wl,--no-undefined CMakeFiles/miral-kiosk.dir/kiosk_main.cpp.o CMakeFiles/miral-kiosk.dir/kiosk_window_manager.cpp.o -o ../../bin/miral-kiosk.bin  ../example-server-lib/libexample-shell-lib.a ../../lib/libmiral.so.4 ../../lib/libmircommon.so.9 ../../lib/libmircookie.so.2 -lnettle /usr/lib/x86_64-linux-gnu/libboost_date_time.so.1.74.0 /usr/lib/x86_64-linux-gnu/libboost_program_options.so.1.74.0 /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.74.0 /usr/lib/x86_64-linux-gnu/libboost_iostreams.so.1.74.0 -ldl /opt/lib/x86_64-linux-gnu/libxkbcommon.so ../../lib/libmircore.so.2 /usr/lib/x86_64-linux-gnu/libboost_system.so.1.74.0 -lwayland-client -lfreetype -Wl,-rpath-link,/srcbuild/mir/lib

**Comment by AlanGriffiths** [comment]
> Looks like CMake 3.22 is throwing an extra `-L/usr/lib/x86_64-linux-gnu` in there

Yes. The mystery is where that comes from and why...

From the context (` -lnettle`) that's probably transitive from mircookie. I see no reason for anything else to be linking against nettle, so try changing the cookie CMakeLists.txt:

```diff
 target_link_libraries(mircookie
-  ${NETTLE_LDFLAGS} ${NETTLE_LIBS}
+  PRIVATE ${NETTLE_LDFLAGS} ${NETTLE_LIBS}
 )
```

I think that will fix it. (Do let me know)

**Comment by n3rdopolis** [comment]
that works

**Comment by n3rdopolis** [comment]
Thanks!

**Comment by AlanGriffiths** [comment]
FWIW what CMake 3.22 does looks wrong, but cleaning up our build recipe avoids that debate
