### ISSUE TITLE
"unused parameter 'type'" warning/error on musl libc

### ISSUE THREAD

**Issue by z3ntu** [MirServer/mir#696]
```
/home/luca/mir/src/common/posix_rw_mutex.cpp: In constructor 'mir::PosixRWMutex::PosixRWMutex(mir::PosixRWMutex::Type)':
/home/luca/mir/src/common/posix_rw_mutex.cpp:53:38: error: unused parameter 'type' [-Werror=unused-parameter]
 mir::PosixRWMutex::PosixRWMutex(Type type)
                                 ~~~~~^~~~
```
(caused by #636)

A crude patch is
```diff
diff --git a/src/common/posix_rw_mutex.cpp b/src/common/posix_rw_mutex.cpp
index f52c423480..4e26ee6a56 100644
--- a/src/common/posix_rw_mutex.cpp
+++ b/src/common/posix_rw_mutex.cpp
@@ -100,6 +100,8 @@ mir::PosixRWMutex::PosixRWMutex(Type type)
             std::system_category(),
             "Failed to set preferred rw-lock mode"}));
     }
+#else
+    (void)type;
 #endif
 
     err = pthread_rwlock_init(&mutex, &attr);
```

**Comment by wmww** [comment]
Your patch looks fine to me
